name: app_usage
description: App usage plugin for Android only
version: 2.0.2
homepage: https://github.com/munkhp/app_usage.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
#flutter:
#  plugin:
#    platforms:
#      android:
#        package: dk.cachet.app_usage
#        pluginClass: AppUsagePlugin
#      ios:
#        pluginClass: AppUsagePlugin
